- hosts: "all"
  gather_facts: true
  vars:
    apache: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    content: "Hello, World!"
  become: true
  tasks:
    - debug: var=apache

    - package:
        name: "{{ apache }}"
        state: present

    - file: 
        path: "/var/www/html/"
        state: directory
        owner: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"
        group: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"

    - copy:
        dest: "/var/www/html/index.html"
        content: "{{content}}"

    - service:
        name: "{{ apache }}"
        state: started
        enabled: true

    - uri:
        url: http://localhost
        return_content: yes
      register: this
      failed_when: "'{{content}}' != this.content"
